[project]
name = "blog-mimi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-blog-plugin>=0.25",
    "mkdocs-blogging-plugin>=2.2.11",
    "mkdocs-git-revision-date-plugin>=0.3.2",
    "mkdocs-macros-plugin>=1.5.0",
    "mkdocs-material>=9.0.0",
    "mkdocs-mermaid2-plugin>=1.2.3",
    "mkdocs-rss-plugin>=1.19.0",
    "mkdocs-terminal>=4.8.0",
    "pymdown-extensions>=12.0.1",
]
